In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4])

print("shape a:{}".format(a.shape))
print("ndim {}".format(a.ndim))
print("size {}".format(a.size))
print(f"dtype {a.dtype}")
print(f"itemsize {a.itemsize}")
print(f"data {a.data}")

shape a:(5,)
ndim 1
size 5
dtype int64
itemsize 8
data <memory at 0x7f5a50590dc0>


In [12]:
a1=np.array([[2,3,4,5],
             [1,4,7,6]])
a2=np.array([[1,1,1],[1,1,1]])


sliced_arr=a1[:2,:2]
print(sliced_arr)


[[2 3]
 [1 4]]


In [15]:
index_arr=a1[[1,1],[2,1]]
print(index_arr)


[7 4]


In [16]:
print(a1.sum())

32


In [20]:
arr=np.array([[25,64],[89,36]])
print(arr.sum())

214


In [21]:
print(np.sqrt(arr))

[[5.         8.        ]
 [9.43398113 6.        ]]


In [23]:
print(arr.T)

[[25 89]
 [64 36]]


In [27]:
b1=np.array([[2,3],[4,5]])
b2=np.array([[5,6],[7,8]])
matrix_multi=np.dot(b1,b2)
print(matrix_multi)

[[31 36]
 [55 64]]


In [34]:
bool=np.array([[True,True],[False,True]])
print("all() with axis none",np.all(bool))
print("all() with axis 0",np.all(bool,axis=0))#any()


all() with axis none False
all() with axis 0 [False  True]


In [38]:
temp=np.arange(9)
print(temp)
re=temp.reshape(3,3)
print(re)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
print(np.take(re,[0,1],axis=1))

[[0 1]
 [3 4]
 [6 7]]


In [52]:
x=np.array([[12,23],[23,34]])
y=np.array([[56,67],[78,89]])
z=np.array([[32,43],[54,65]])
v=np.vstack((x,y,z))
h=np.hstack((x,y,z))

print("vstack:",v)
print("hstack:",h)

vstack: [[12 23]
 [23 34]
 [56 67]
 [78 89]
 [32 43]
 [54 65]]
hstack: [[12 23 56 67 32 43]
 [23 34 78 89 54 65]]


In [54]:
h_split=np.hsplit(h,3)
print("split:",split)
v_split=np.vsplit(h,2)
print("vsplit:",v_split)

split: [array([[12, 23],
       [23, 34]]), array([[56, 67],
       [78, 89]]), array([[32, 43],
       [54, 65]])]
vsplit: [array([[12, 23, 56, 67, 32, 43]]), array([[23, 34, 78, 89, 54, 65]])]


In [55]:
arr=np.array([23,34,45,67])
print("Sqrt: ",np.sqrt(arr))#Returns the square root of each element 
print("Exp: ",np.exp(arr))     #Returns the exponentials of each element
print("Sin: ",np.sin(arr))     #Returns the sin of each element
print("Cos: ",np.cos(arr))     #Returns the cosine of each element
print("Log: ",np.log(arr))     #Returns the logarithm of each element
print("Sum: ",np.sum(arr))     #Returns the sum total of elements in the array
print("Std: ",np.std(arr))     #Returns the standard deviation of in the array

Sqrt:  [4.79583152 5.83095189 6.70820393 8.18535277]
Exp:  [9.74480345e+09 5.83461743e+14 3.49342711e+19 1.25236317e+29]
Sin:  [-0.8462204   0.52908269  0.85090352 -0.85551998]
Cos:  [-0.53283302 -0.84857027  0.52532199 -0.5177698 ]
Log:  [3.13549422 3.52636052 3.80666249 4.20469262]
Sum:  169
Std:  16.269219403523945


In [56]:
print("random: {}\n".format(np.random.random(20)));

print("rand: {}\n".format(np.random.rand(3, 4)));

print("randint: {}\n".format(np.random.randint(0, 100, 20)));

print("permutation: {}\n".format(np.random.permutation(np.arange(20))));


random: [0.75000255 0.30506944 0.54549621 0.17886853 0.66273098 0.9848601
 0.25906072 0.89953354 0.58271799 0.52005519 0.76385927 0.15353349
 0.25997079 0.40742641 0.74704434 0.13700975 0.56253971 0.46360888
 0.34015641 0.97700372]

rand: [[0.73323318 0.28554358 0.87017163 0.41384209]
 [0.69557188 0.33574807 0.29475836 0.58715463]
 [0.79983732 0.56497802 0.47168692 0.24064127]]

randint: [88 97 33 36 56 42 32 89 10 84 88 93 37 77 95 88 72 10 47 47]

permutation: [10 13  1  3  6 18 15 14 19  4  9 17  8 16 12  2  5  0  7 11]

